# Generated by Django 6.0.3 on 2026-03-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Student', max_length=100)),
                ('quizzes_taken', models.IntegerField(default=0)),
                ('notes_summarized', models.IntegerField(default=0)),
                ('chat_sessions', models.IntegerField(default=0)),
                ('materials_viewed', models.IntegerField(default=0)),
                ('streak_days', models.IntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
